Remove texplate interpolation when configuring director.

diff --git a/ci/tasks/configure-director/task b/ci/tasks/configure-director/task
--- a/ci/tasks/configure-director/task
+++ b/ci/tasks/configure-director/task
@@ -3,23 +3,19 @@
 main() {
   om -v
 
-  local cwd=${PWD}
-  local opsman_dns=$(jq -r .ops_manager_dns < "${cwd}/env-state/metadata")
+  metadata="${PWD}/env-state/metadata"
+  opsman_dns=$(cat "${metadata}" | yq -r .stable_config | jq -r .ops_manager_dns)
 
-  set +x
-    WITH_CERT=$(cat "${cwd}/env-state/metadata" | jq --arg terraformingca "${CA_CERT}" '. + {terraforming_ca_cert: $terraformingca}')
-    echo "${WITH_CERT}" > "${PWD}/config.yml"
-  set -x
-
-  texplate execute "${TEMPLATE_PATH}" \
-    -f  "${PWD}/config.yml" \
-    -o yaml > "${cwd}/director-config.yml"
+  if [[ "${opsman_dns}" == "null" ]]; then
+    echo "missing ops manager dns, exiting"
+    exit 1
+  fi
 
   set +x
     om -t "https://${opsman_dns}" -k -o 30 configure-authentication -dp "${OM_PASSWORD}"
   set -x
 
-  om -t "https://${opsman_dns}" -k configure-director --config "${cwd}/director-config.yml"
+  om -t "https://${opsman_dns}" -k configure-director --config "${PWD}/env-state/director.yml"
 }
 
 main "$@"
